version: "3.9"
services:
  webserver-hermail:
    build:
      context: ${PWD}/.docker
      args:
        PHP_VERSION: 8.2
    env_file:
      - .env
    container_name: 'webserver-hermail'
    restart: 'unless-stopped'
    ports:
      - "41:80"
    volumes:
      - ./:/var/www/html
      - ${PWD}/.docker/config/webserver/php.ini:/usr/local/etc/php/php.ini
      - ${PWD}/.docker/config/webserver/vhosts:/etc/apache2/sites-enabled
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_CS_FIXER_IGNORE_ENV: 1
  mailer:
    image: schickling/mailcatcher
    ports: [ "1025", "1080" ]
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
