controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

heath_check:
    path:       /healthcheck
    controller: App\Controller\HealthcheckController
    methods:    GET

send:
    path:       /send
    controller: App\Controller\SendMailController
    methods:    POST

status:
    path:       /status/{id}
    controller: App\Controller\StatusMailController
    methods:    GET
